name: Auto Run Radio Station Manager

on:
  workflow_dispatch: # Allows the workflow to be triggered manually from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp tqdm requests

    - name: Run Full Rescan, Verify, and Update README
      run: |
        python helpers/radio_station_manager.py --auto-run --fetch --verify --count
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Automated: Full rescan, verify, and README update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
