name: Get Stations

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours (at 00:00 and 12:00 UTC)

jobs:
  update_stations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp tqdm configparser

    - name: Run the station manager script
      run: python helpers/radio_station_manager.py --auto-run

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md with latest station count"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
